### ISSUE TITLE
Initiators Work

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#173]
### Initiators Work

Initiate workflows based on some event driven architecture
 
### Acceptance Criteria
*Acceptance criteria required to implement the epic*
S3 Listener / Airflow Eval/Initiation” item can be deployed via
Marketplace, using Management Console. TBD : Possibly deployed as
two separate MP items (listener + initiator).
iii) Modify an Evaluator lambdas to prove a change can be made. A
minimum of 2 lambda evaluators should be exercised as part of this
demo.
iv) Run SRL Data:
(1) Drop data files into S3 bucket
(2) Show that SNS, SQS, & lambda(s) are properly invoked
 (3) Show that DAG(s) are invoked/running in Airflow
(4) [OPTIONAL] Prove ingestion of EDR product can flow back to
another evaluation that runs RDRgen

### Work Tickets
*Link to work tickets required to implement the epic*
- [x] [Mock Up Initiators Configuration Template for Review](https://github.com/unity-sds/unity-cs/issues/385)
- [x] [Setup Initiators Github repos](https://github.com/unity-sds/unity-on-demand/issues/37)
- [x] [Create Schema that Validates Initiators Configuration](https://github.com/unity-sds/unity-on-demand/issues/38)
- [x] [Create SRL Initiator for EDRGen (.dat + .emd)](https://github.com/unity-sds/unity-sps/issues/287)
- [x] [Create new Initiators action type that submits OGC](https://github.com/unity-sds/unity-cs/issues/413)
- [x] [Initiators:  Create PR of code changes made to initiators repo](https://github.com/unity-sds/unity-cs/issues/435)
- [ ] [Initiators: Research and prototype CMR trigger options (POLLING)](https://github.com/unity-sds/unity-cs/issues/437)	
- [x] [Initiators: High-level logging & Traceability of initiators/triggers events](https://github.com/unity-sds/unity-cs/issues/439)
- [x] [Initiators: Move lambda logic into Airflow DAG](https://github.com/unity-sds/unity-cs/issues/432)
- [x] [Initiators: Breakout vic2png into a separate Airflow DAG](https://github.com/unity-sds/unity-cs/issues/433)
- [x] [Initiators: Schedule and Do Airflow / vic2png / round-trip demo](https://github.com/unity-sds/unity-cs/issues/434)
- [x] [Initiators: Review and merge Initiators PR](https://github.com/unity-sds/unity-cs/issues/436)
- [x] [Initiators: Schedule and Do Demo of CMR triggering](https://github.com/unity-sds/unity-cs/issues/438)
- [ ] [Initiators: Schedule and Do a Demo of Accountability / Traceability / Logging](https://github.com/unity-sds/unity-cs/issues/440)
- [ ] [Initiators: Research and prototype CMR trigger options (Subscription)](https://github.com/unity-sds/unity-cs/issues/455)	

### Dependencies
*Other epics or outside tickets required for this to work*
- [ ] TBC

### Associated Risks
*links to risk issues associated with this epic*
- [ ] TBC

**Comment by mike-gangl** [comment]
Will demonstrate this in the 1st sprint of 24.3. This will need to be integrated into the SPS work at some point.

**Comment by pymonger** [comment]
Please check off:
- https://github.com/unity-sds/unity-cs/issues/433
- https://github.com/unity-sds/unity-cs/issues/434

**Comment by LucaCinquini** [comment]
This ticket can be closed, Gerald successfully demonstrated a full SPS prototype that chains EDRgen, RDRgen and Vic2png

**Comment by brianlee731** [comment]
Closing this ticket as we have demonstrated the core initiator framework for SRL.
