### ISSUE TITLE
Application Package standardization -stage in/out to platform Implementation

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#206]
### Application Package standardization -stage in/out to platform Implementation

This ticket is to track the feature work to align the MDPS application package generator and platforms with the OGC Application package best practices Specification.

Design Ticket is located at https://github.com/unity-sds/unity-project-management/issues/187
 
#### Application Packages
- The algorithm CWL specifies file/data inputs as Directory types, and in that directory will/can read a catalog.json file to get the data its relying on (A.2.1). This changes the input type from a catalog.json location to a Directory.
- The algorithm writes outputs to a Directory along with a stac catalog catalog.json), describing the files in that directory. (A.3.1). Outputs have always been a directory type

#### Platform
- the platform will be able to take an 'input' parameter (a valid STAC document or URL to a stac document) and stage those inputs in a single directory for usage by an application package. 
  - The platform shall be capable of retrieving URLs to stac documents from CMR or from the UDS Catalog
- The platform shall generate a catalog.json file and associated item files or entries for all staged data products and add it the directory containing staged data.
- After execution of a CWL workflow, the platform shall read data from a "process_output" directory and persist (stage-out) all data products specified in the catalog.json entry.
- The platform can determine the S3 bucket to which files are persisted through environment or SSM parameters. These are not specified by the user (unless we want to override them?)
- Items like EDL passwords, Unity passwords will default to SSM parameters, and those must be created prior to invocation of the job run (e.g. using the management console, a user can create SSM parameters that map to EDL username/passwords). 

Running the Example Application Package:

Current inputs required to run the Unity-example-application

```
input_json = """
    {{
      "stage_in": {{
        "stac_json": "https://raw.githubusercontent.com/unity-sds/unity-tutorial-application/main/test/stage_in/stage_in_results.json",
        "downloading_roles": "",
        "downloading_keys": "data",
        "download_type": "HTTP",
        "edl_username": null,
        "edl_password_type": "",
        "edl_password": "",
        "unity_client_id": "",
        "unity_stac_auth": "NONE"
      }},
      "parameters": {{
        "output_collection": "urn:nasa:unity:{0}:{1}:unity-tutorial___1",
        "summary_table_filename": "summary_table_{2}.txt"
      }},
      "stage_out": {{
        "staging_bucket": "{3}",
        "collection_id": "urn:nasa:unity:{0}:{1}:unity-tutorial___1",
        "result_path_prefix": "stage_out"
      }}
    }}
    """.format(
        project, venue, date, s3bucket
    )
```

After stage-in/out:

```
input_json = """
    {{
        "input": "https://raw.githubusercontent.com/unity-sds/unity-tutorial-application/main/test/stage_in/stage_in_results.json", # -- because this has the 'input' key, this will be staged
        # "input_downloading_roles": "" --  for overriding default behaviors?
        # "input_downloading_keys": "data", -- for overriding default behaviors
        # "input_download_type": "HTTP", -- for overriding default behaviors
        "output_collection": "urn:nasa:unity:{0}:{1}:unity-tutorial___1", -- inputs to the app pacakge
        "summary_table_filename": "summary_table_{2}.txt" -- inputs to the app package
        # "staging_bucket": "{3}", -- should be discovered by platform through SSM/env
    }}
    """.format(
        project, venue, date, s3bucket
    )
```

### Work Tickets
*Link to work tickets required to implement the epic*
- [ ] TBC (to be created)

### Dependencies
*Other epics or outside tickets required for this to work*
- [ ] TBC

### Associated Risks
*links to risk issues associated with this epic*
- [ ] TBC

**Comment by LucaCinquini** [comment]
System Validation Criteria:
o Gherkin tests for successful execution of each target use case (EMIT, SBG, ASPIS) using the decomposed stage-in/process/stage-out DAG, where (at least) the process Task is executed via a CWL workflow.

**Comment by LucaCinquini** [comment]
A first prototype version of a modular stage-in / process / stage-out DAG is part of the 24.4 release. The team needs to create more examples of modularized CWL workflows which can be used for further testing.

**Comment by brianlee731** [comment]
Tickets remaining:
- [ ] https://github.com/unity-sds/app-pack-generator/issues/25 (Jupyter kernel default)
- [ ] https://github.com/unity-sds/unity-ads-deployment/issues/180 (Gitlab Runner update)
- [ ] https://github.com/unity-sds/unity-app-generator/issues/20 (Remove bundling of stage in/out from unity-app-generator)

**Comment by rtapella** [comment]
what application is used to test these? is the https://github.com/unity-sds/unity-tutorial-application used for anything?

if not, we will need to also update unity-tutorial-application and associated documentation/tutorials

**Comment by brianlee731** [comment]
We can get rid of the unity-tutorial-application; I had forked it from unity-example-application in case we wanted to change anything for the tutorial. We ended up just using unity-example-application as is. 

With that being said, I'll delete the repo unless anyone has concerns about removing it.

**Comment by rtapella** [comment]
It looks like Mike did some work with the updated stage in on unity-tutorial-application?

**Comment by mcduffie** [comment]
@rtapella Are you referring to [this](https://github.com/mike-gangl/unity-OGC-example-application/tree/main)?

**Comment by rtapella** [comment]
Uh. Hmm maybe that’s another one?

Brian and I are talking about:
https://github.com/unity-sds/unity-tutorial-application
Vs
https://github.com/unity-sds/unity-example-application

**Comment by rtapella** [comment]
Oh I guess the one you linked is a fork of the second (example-application)

**Comment by mcduffie** [comment]
I've been updating [unity-example-application](https://github.com/unity-sds/unity-example-application) for fixes to app-pack-generator. I will incorporate changes Mike made to his fork into that version.

**Comment by rtapella** [comment]
ok ... at that point we can just use the example-application and archive the tutorial-application?

will you merge your fork of example-application back to the main one? Or do we use one of those as the single official example/demo app?

**Comment by brianlee731** [comment]
@rtapella I agree. We can archive the tutorial-application.

**Comment by mcduffie** [comment]
I have already merged in Mike's changes [here](https://github.com/unity-sds/unity-example-application/tree/optional_stage_inout).

**Comment by LucaCinquini** [comment]
SPS is working on converting several workflows to the modularized design.
@nikki-t and @brianlee731 converted the EMIT workflow, @LucaCinquini write a nightly test for it.
Next on the list is the SBG end-to-end workflow.

**Comment by brianlee731** [comment]
NOTE: Focus on SBG isofit and pre-process. Need independent workflow for SBG isofit. Action: @brianlee731 modular design for SBG isofit.

**Comment by mike-gangl** [comment]
there existing (current) workflows of the preprocess and ISOFIT workflows:

https://github.com/unity-sds/sbg-workflows/tree/main/isofit

This will need to be updated for the new app package format.

**Comment by brianlee731** [comment]
Completed testing on SBG Pre-process on the Modular DAG. Here's some info:

STAC Json: https://raw.githubusercontent.com/brianlee731/SBG-unity-preprocess-mod/refs/heads/main/test/stage-in/featureCollection.json

Workflow: http://awslbdockstorestack-lb-1429770210.us-west-2.elb.amazonaws.com:9998/api/ga4gh/trs/v2/tools/%23workflow%2Fdockstore.org%2Fedwinsarkissian%2FSBG-unity-preprocess-mod/versions/4/PLAIN-CWL/descriptor/%2Fprocess.cwl
